### ISSUE TITLE
Compiler warnings when building talk.wasm

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eosio-web-ide#10]
The following IDE warnings are received in the GitPod "Problems" window when building talk.wasm/.abi (screenshot since I couldn't get gitpod to copy/paste the output of the Problems tab):

![image](https://user-images.githubusercontent.com/667305/72297732-853b3e00-362a-11ea-819d-fc0ed9bb6ed6.png)

These warnings should be cleaned up since this is a demo.

I also see this output in the Terminal window:

```
gitpod /workspace/eosio-web-ide $ eosio-cpp contract/talk.cpp
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <post> does not have a ricardian contract
```

**Comment by tbfleming** [comment]
That's `clangd`. It doesn't understand the CDT's extensions yet. That's on the very long backlog of potential CDT enhancements.

**Comment by gleehokie** [comment]
> That's clangd. It doesn't understand the CDT's extensions yet.
Ahh yes, I remember you telling me about that.  Add it to the list!

**Comment by tbfleming** [comment]
New issue: https://github.com/EOSIO/eosio.cdt/issues/788 . It was only on paper and in our heads.
