### ISSUE TITLE
Gitpod webpage unresponsive when trying to close the "Preview" pane

### ISSUE THREAD

**Issue by bogniq** [EOSIO/eosio-web-ide#35]
**System config**
OS: macOS 10.15.5
Browser: Chrome 86.0.4240.183 (not using Gitpod extension)

**Steps to trigger the problem:**
1. Follow each step in the "Instructions" section of README.md. After running `gp preview $(gp url 8000)`, the Preview pane is opened and display the frontend webpage.

2. Try to close this panel by clicking "Close" on the context menu.
<img width="564" alt="close_preview_panel" src="https://user-images.githubusercontent.com/73851079/98719619-fdaf8000-235d-11eb-8ea9-e41687c8fc26.png">

3. The webpage for Gitpod becomes unresponsive. I need to close this weppage and restart the Gitpod workspace to make it work again.
<img width="432" alt="page_unresponsive" src="https://user-images.githubusercontent.com/73851079/98719702-128c1380-235e-11eb-839c-79f5c4bf6a52.png">

**Other notes**
- I'm new to Gitpod and eosio-web-ide. So I'm not sure if this problem is caused by Gitpod itself or some config here. 
- If other user gets the same problem, one workaround is to use external browser for the frontend webpage (in "Open Ports" tab -> "8000", select "Open Browser").

**Comment by sanaraufx** [comment]
This seems to be a Gitpod issue. We are closing it to focus on other priorities. Please reopen if needed.
