### ISSUE TITLE
how to switch the eosio.cdt version

### ISSUE THREAD

**Issue by infinityhacker** [EOSIO/eosio-web-ide#7]
There is no tab on version switching in user page, and where is it

**Comment by tbfleming** [comment]
Each tagged version of the docker container has a single eosio.cdt version. So far we only have a single release. Once we add additional releases, you can choose versions by editing the `image` section of `.gitpod.yml`

**Comment by sanaraufx** [comment]
Closing this issue to focus on more recent items. We do not have any plans to introduce additional releases at this time. Thank you.
