### ISSUE TITLE
gitpod Error

### ISSUE THREAD

**Issue by rubenabix** [EOSIO/eosio-web-ide#9]
If you go to https://gitpod.io/#https://github.com/EOSIO/eosio-web-ide or other account link you will get:

Sorry, something went wrong 😓
Error: Request createWorkspace failed with message: 5 NOT_FOUND: cannot resolve base image: not found.

**Comment by tbfleming** [comment]
Reported to gitpod: https://github.com/gitpod-io/gitpod/issues/895

**Comment by tbfleming** [comment]
Fixed by gitpod
